//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gozcu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AyarlarTablosu
    {
        public int Id { get; set; }
        public string BinanceApiKey { get; set; }
        public string BinanceApiSecret { get; set; }
        public decimal EmirBoyutuUSDT { get; set; }
        public string HaricSemboller { get; set; }
        public string IslemPeriyot { get; set; }
        public int BacktestBarSayisi { get; set; }
        public int BacktestEsikKarOrani { get; set; }
        public decimal KarAlOran { get; set; }
        public decimal TakipEdenDurdurOran { get; set; }
        public string TelegramApiToken { get; set; }
        public string TelegramLogChannel { get; set; }
        public string TelegramIslemChannel { get; set; }
        public int IslemTipi { get; set; }
        public string IslemPeriyotAralik { get; set; }
    }
}
