//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gozcu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RehberTablo
    {
        public int Id { get; set; }
        public string Sembol { get; set; }
        public string Periyot { get; set; }
        public string Parametreler { get; set; }
        public Nullable<decimal> NetKar { get; set; }
        public Nullable<decimal> BurutKar { get; set; }
        public Nullable<decimal> BurutZarar { get; set; }
        public Nullable<decimal> ProfitFactor { get; set; }
        public Nullable<int> BarSayisi { get; set; }
        public Nullable<int> IslemSayisi { get; set; }
        public Nullable<int> BasariliIslemSayisi { get; set; }
        public Nullable<int> KarAlSayisi { get; set; }
        public Nullable<int> TakipEdenDurdurSayisi { get; set; }
        public Nullable<int> ZararDurdurSayisi { get; set; }
        public Nullable<int> StratejiSatSayisi { get; set; }
    }
}
