//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operasyon.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlgoTradeOttDbEntities : DbContext
    {
        public AlgoTradeOttDbEntities()
            : base("name=AlgoTradeOttDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvciSonuclari> AvciSonuclari { get; set; }
        public virtual DbSet<AyarlarTablosu> AyarlarTablosu { get; set; }
        public virtual DbSet<FiyatKontrolTablosu> FiyatKontrolTablosu { get; set; }
        public virtual DbSet<IslemTablosu> IslemTablosu { get; set; }
        public virtual DbSet<RehberTablo> RehberTablo { get; set; }
        public virtual DbSet<StratejiParametreleri> StratejiParametreleri { get; set; }
        public virtual DbSet<StratejiyeTakilanlar> StratejiyeTakilanlar { get; set; }
        public virtual DbSet<temp_AvciSonuclari> temp_AvciSonuclari { get; set; }
        public virtual DbSet<temp_RehberTablo> temp_RehberTablo { get; set; }
    }
}
