//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operasyon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StratejiyeTakilanlar
    {
        public int Id { get; set; }
        public string Sembol { get; set; }
        public string Periyot { get; set; }
        public string Parametreler { get; set; }
        public Nullable<int> GecenBarSayisi { get; set; }
        public Nullable<decimal> AlSinyalFiyat { get; set; }
        public Nullable<decimal> MevcutFiyat { get; set; }
        public string Sebep { get; set; }
    }
}
